### ISSUE TITLE
The limitation

### ISSUE THREAD

**Issue by YashJha05** [irving-rs/guess_number#1]
Instead of giving the user 7 opportunities, you should include unlimited and add a second player option which will make the game even more fun. I code in C so if I am adding a second player, I would run the random number generating code before the second user’s input again to ensure no cheating.

**Comment by irving-rs** [comment]
Hello @YashJha05 - I think that 7 opportunities is fine because if you use a good algorithm, the secret number can be found after a maximum of 7 guesses. In relation with the number of users, by the moment I do not plan on increasing the "game capacity", I mean, I want this project to stay as a prototype. Later, when I learn to use GUI, I will return to make a major update.
